apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: github-actions-demo
  labels:
    app: github-actions-demo
spec:
  selector:
    matchLabels:
      app: github-actions-demo
  template:
    metadata:
      labels:
        app: github-actions-demo
        istio-injection: enabled
    spec:
      containers:
      - name: github-actions-demo
        image: vfarcic/github-actions-demo
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
  strategy:
    canary:
      canaryService: github-actions-demo-canary
      stableService: github-actions-demo
      trafficRouting:
        istio:
          virtualService:
            name: github-actions-demo
            routes:
            - primary
      steps:
      - setWeight: 10
      - pause: {duration: 2m}
      - setWeight: 30
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      analysis:
        templates:
        - templateName: github-actions-demo
        startingStep: 2
        args:
        - name: service-name
          value: "github-actions-demo-canary.production.svc.cluster.local"

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: github-actions-demo
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] >= 0.8
    failureCondition: result[0] < 0.8
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: |
          sum(irate(
            istio_requests_total{  
              reporter="source",
              destination_service=~"{{args.service-name}}",
              response_code=~"2.*"
            }[2m]
          )) / sum(irate(
            istio_requests_total{
              reporter="source",
              destination_service=~"{{args.service-name}}"
            }[2m]
          ))
  - name: avg-req-duration
    interval: 10s
    successCondition: result[0] <= 1000
    failureCondition: result[0] > 1000
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: |
          sum(irate(
            istio_request_duration_milliseconds_sum{
              reporter="source",
              destination_service=~"{{args.service-name}}"
            }[2m]
          )) / sum(irate(
            istio_request_duration_milliseconds_count{
              reporter="source",
              destination_service=~"{{args.service-name}}"
            }[2m]
          ))
      
---

apiVersion: v1
kind: Service
metadata:
  name: github-actions-demo-canary
  labels:
    app: github-actions-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: github-actions-demo
