name: feature
on:
  push:
    branches-ignore:
    - master
    - main
  pull_request:
    branches:
    - "!master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # There is no need to checkout. It's done directly by buildkit.
    # - name: Checkout
    #   uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
